name: Test VPS Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔧 Test SSH Connection
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: ${{ secrets.VPS_PORT || '22' }}
        script: |
          echo "=== Basic System Information ==="
          whoami
          pwd
          uname -a
          
          echo "=== Directory Structure ==="
          ls -la /var/www/ 2>/dev/null || echo "/var/www/ not accessible"
          ls -la /var/www/vhosts/ 2>/dev/null || echo "/var/www/vhosts/ not accessible"
          ls -la /var/www/vhosts/${{ secrets.DOMAIN_NAME }}/ 2>/dev/null || echo "Domain directory not accessible"
          ls -la /var/www/vhosts/${{ secrets.DOMAIN_NAME }}/httpdocs/ 2>/dev/null || echo "httpdocs not accessible"
          
          echo "=== Home Directory ==="
          ls -la ~
          
          echo "=== Available Commands ==="
          which node || echo "node not found"
          which npm || echo "npm not found"
          which tar || echo "tar not found"
          which mkdir || echo "mkdir not found"
          
          echo "=== Process Information ==="
          ps aux | grep -i node | head -5 || echo "No node processes"
          
          echo "=== Test completed ==="